sudo: true
language: python

os: "linux"

python:
  - "2.7"
  - "3.6"

before_install: pip install numpy cython matplotlib seaborn multiprocess

install: python setup.py install

script: make

notifications:
  email: false
