sudo: true
language: python
python:
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 -y -qq
  - export CXX="g++-4.8"
  - make CXX=g++-4.8 OPENMP=yes

install:
  - pip install .

script: make test
