sudo: true
language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 gcc -y -qq
  - pip install numpy pandas scipy cython matplotlib seaborn multiprocess

install:
  - python setup.py install

script: make
