sudo: true
language: python
python:
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 gcc -y -qq
  - make CXX=g++-4.8 OPENMP=yes
  - pip install numpy pandas cython matplotlib

install:
  - python setup.py install

script: make test
